version: '3.8'
services:
  redis-server:
    image: 'redis'
  node_app:
    build: .
    depends_on:
      redis-server:
        condition: service_started
    environment:
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
    ports:
      - "5000:8001"

